[workspace]
authors = ["s1f10230101 <s1f102301011@iniad.org>"]
channels = ["conda-forge", "main", "r", "msys2", "https://repo.anaconda.com/pkgs/main", "https://repo.anaconda.com/pkgs/r"]
name = "ict2025-ds-greykite"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
anyio = { version = "==4.11.0", build = "pyhcf101f3_0" }
appnope = { version = "==0.1.4", build = "pyhd8ed1ab_1" }
argon2-cffi = { version = "==25.1.0", build = "pyhd8ed1ab_0" }
arrow = { version = "==1.3.0", build = "pyhd8ed1ab_1" }
asttokens = { version = "==3.0.0", build = "pyhd8ed1ab_1" }
async-lru = { version = "==2.0.5", build = "pyh29332c3_0" }
attrs = { version = "==25.3.0", build = "pyh71513ae_0" }
babel = { version = "==2.17.0", build = "pyhd8ed1ab_0" }
beautifulsoup4 = { version = "==4.13.5", build = "pyha770c72_0" }
bleach = { version = "==6.2.0", build = "pyh29332c3_4" }
bleach-with-css = { version = "==6.2.0", build = "h82add2a_4" }
cached-property = { version = "==1.5.2", build = "hd8ed1ab_1" }
cached_property = { version = "==1.5.2", build = "pyha770c72_1" }
certifi = { version = "==2025.8.3", build = "pyhd8ed1ab_0" }
cffi = { version = "==1.17.1", build = "py310h497396d_0" }
charset-normalizer = { version = "==3.4.3", build = "pyhd8ed1ab_0" }
clarabel = { version = "==0.11.1", build = "py310h7b52fdd_0" }
comm = { version = "==0.2.3", build = "pyhe01879c_0" }
cvxpy = { version = "==1.7.2", build = "py310hb6292c7_0" }
cvxpy-base = { version = "==1.7.2", build = "py310h03dc5a2_0" }
debugpy = { version = "==1.8.17", build = "py310h7b404bc_0" }
decorator = { version = "==5.2.1", build = "pyhd8ed1ab_0" }
defusedxml = { version = "==0.7.1", build = "pyhd8ed1ab_0" }
ecos = { version = "==2.0.14", build = "py310hfdc7867_2" }
exceptiongroup = { version = "==1.3.0", build = "pyhd8ed1ab_0" }
executing = { version = "==2.2.1", build = "pyhd8ed1ab_0" }
expat = { version = "==2.7.1", build = "h313beb8_0" }
fqdn = { version = "==1.5.1", build = "pyhd8ed1ab_1" }
h11 = { version = "==0.16.0", build = "pyhd8ed1ab_0" }
h2 = { version = "==4.3.0", build = "pyhcf101f3_0" }
hpack = { version = "==4.1.0", build = "pyhd8ed1ab_0" }
httpcore = { version = "==1.0.9", build = "pyh29332c3_0" }
httpx = { version = "==0.28.1", build = "pyhd8ed1ab_0" }
hyperframe = { version = "==6.1.0", build = "pyhd8ed1ab_0" }
icu = { version = "==75.1", build = "hfee45f7_0" }
idna = { version = "==3.10", build = "pyhd8ed1ab_1" }
importlib-metadata = { version = "==8.7.0", build = "pyhe01879c_1" }
ipykernel = { version = "==6.30.1", build = "pyh92f572d_0" }
ipython = { version = "==8.37.0", build = "pyh8f84b5b_0" }
isoduration = { version = "==20.11.0", build = "pyhd8ed1ab_1" }
jedi = { version = "==0.19.2", build = "pyhd8ed1ab_1" }
jinja2 = { version = "==3.1.6", build = "pyhd8ed1ab_0" }
joblib = { version = "==1.5.2", build = "pyhd8ed1ab_0" }
json5 = { version = "==0.12.1", build = "pyhd8ed1ab_0" }
jsonpointer = { version = "==3.0.0", build = "py310hbe9552e_2" }
jsonschema = { version = "==4.25.1", build = "pyhe01879c_0" }
jsonschema-specifications = { version = "==2025.9.1", build = "pyhcf101f3_0" }
jsonschema-with-format-nongpl = { version = "==4.25.1", build = "he01879c_0" }
jupyter-lsp = { version = "==2.3.0", build = "pyhcf101f3_0" }
jupyter_client = { version = "==8.6.3", build = "pyhd8ed1ab_1" }
jupyter_core = { version = "==5.8.1", build = "pyh31011fe_0" }
jupyter_events = { version = "==0.12.0", build = "pyh29332c3_0" }
jupyter_server = { version = "==2.17.0", build = "pyhcf101f3_0" }
jupyter_server_terminals = { version = "==0.5.3", build = "pyhd8ed1ab_1" }
jupyterlab = { version = "==4.4.7", build = "pyhd8ed1ab_0" }
jupyterlab_pygments = { version = "==0.3.0", build = "pyhd8ed1ab_2" }
jupyterlab_server = { version = "==2.27.3", build = "pyhd8ed1ab_1" }
krb5 = { version = "==1.21.3", build = "h237132a_0" }
lark = { version = "==1.3.0", build = "pyhd8ed1ab_0" }
libblas = { version = "==3.9.0", build = "36_h51639a9_openblas" }
libcblas = { version = "==3.9.0", build = "36_hb0561ab_openblas" }
libcxx = { version = "==20.1.8", build = "h8869778_0" }
libedit = { version = "==3.1.20250104", build = "pl5321hafb1f1b_0" }
libffi = { version = "==3.4.4", build = "hca03da5_1" }
libgfortran = { version = "==15.1.0", build = "hfdf1602_1" }
libgfortran5 = { version = "==15.1.0", build = "hb74de2c_1" }
liblapack = { version = "==3.9.0", build = "36_hd9741b5_openblas" }
libopenblas = { version = "==0.3.30", build = "openmp_h60d53f8_2" }
libosqp = { version = "==0.6.3", build = "h5833ebf_1" }
libqdldl = { version = "==0.1.7", build = "hb7217d7_0" }
libsodium = { version = "==1.0.20", build = "h99b78c6_0" }
libsqlite = { version = "==3.50.4", build = "h4237e3c_0" }
libzlib = { version = "==1.3.1", build = "h5f15de7_0" }
llvm-openmp = { version = "==20.1.8", build = "hbb9b287_2" }
markupsafe = { version = "==3.0.2", build = "py310hc74094e_1" }
matplotlib-inline = { version = "==0.1.7", build = "pyhd8ed1ab_1" }
mistune = { version = "==3.1.4", build = "pyhcf101f3_0" }
narwhals = { version = "==2.5.0", build = "pyhcf101f3_0" }
nbclient = { version = "==0.10.2", build = "pyhd8ed1ab_0" }
nbconvert-core = { version = "==7.16.6", build = "pyh29332c3_0" }
nbformat = { version = "==5.10.4", build = "pyhd8ed1ab_1" }
ncurses = { version = "==6.5", build = "hee39554_0" }
nest-asyncio = { version = "==1.6.0", build = "pyhd8ed1ab_1" }
notebook-shim = { version = "==0.2.4", build = "pyhd8ed1ab_1" }
openssl = { version = "==3.5.3", build = "h5503f6c_1" }
osqp = { version = "==0.6.7.post3", build = "py310h3420790_1" }
overrides = { version = "==7.7.0", build = "pyhd8ed1ab_1" }
packaging = { version = "==25.0", build = "pyh29332c3_1" }
pandocfilters = { version = "==1.5.0", build = "pyhd8ed1ab_0" }
parso = { version = "==0.8.5", build = "pyhcf101f3_0" }
patsy = { version = "==1.0.1", build = "pyhd8ed1ab_1" }
pexpect = { version = "==4.9.0", build = "pyhd8ed1ab_1" }
pickleshare = { version = "==0.7.5", build = "pyhd8ed1ab_1004" }
pip = { version = "==25.2", build = "pyhc872135_0" }
platformdirs = { version = "==4.4.0", build = "pyhcf101f3_0" }
plotly = { version = "==6.3.0", build = "pyhd8ed1ab_0" }
prometheus_client = { version = "==0.23.1", build = "pyhd8ed1ab_0" }
prompt-toolkit = { version = "==3.0.52", build = "pyha770c72_0" }
psutil = { version = "==7.1.0", build = "py310hfe3a0ae_0" }
ptyprocess = { version = "==0.7.0", build = "pyhd8ed1ab_1" }
pure_eval = { version = "==0.2.3", build = "pyhd8ed1ab_1" }
pycparser = { version = "==2.22", build = "pyh29332c3_1" }
pygments = { version = "==2.19.2", build = "pyhd8ed1ab_0" }
pyobjc-core = { version = "==11.0", build = "py310h4e4eb3c_0" }
pyobjc-framework-cocoa = { version = "==11.0", build = "py310h4e4eb3c_0" }
pysocks = { version = "==1.7.1", build = "pyha55dd90_7" }
python = { version = "==3.10.15", build = "hdce6c4c_2_cpython" }
python-dateutil = { version = "==2.9.0.post0", build = "pyhe01879c_2" }
python-fastjsonschema = { version = "==2.21.2", build = "pyhe01879c_0" }
python-json-logger = { version = "==2.0.7", build = "pyhd8ed1ab_0" }
python-tzdata = { version = "==2025.2", build = "pyhd8ed1ab_0" }
python_abi = { version = "==3.10", build = "8_cp310" }
pytz = { version = "==2025.2", build = "pyhd8ed1ab_0" }
pyyaml = { version = "==6.0.2", build = "py310hc74094e_2" }
pyzmq = { version = "==27.1.0", build = "py310hc4a7dca_0" }
qdldl-python = { version = "==0.1.7.post5", build = "np20py310h51fdda9_1" }
readline = { version = "==8.3", build = "h0b18652_0" }
referencing = { version = "==0.36.2", build = "pyh29332c3_0" }
requests = { version = "==2.32.5", build = "pyhd8ed1ab_0" }
rfc3339-validator = { version = "==0.1.4", build = "pyhd8ed1ab_1" }
rfc3986-validator = { version = "==0.1.1", build = "pyh9f0ad1d_0" }
rfc3987-syntax = { version = "==1.1.0", build = "pyhe01879c_1" }
rpds-py = { version = "==0.27.1", build = "py310h7018d9b_1" }
scs = { version = "==3.2.7.post2", build = "default_py310h5fa3e39_1" }
send2trash = { version = "==1.8.3", build = "pyh31c8845_1" }
setuptools = { version = "==78.1.1", build = "py310hca03da5_0" }
six = { version = "==1.17.0", build = "pyhe01879c_1" }
sniffio = { version = "==1.3.1", build = "pyhd8ed1ab_1" }
soupsieve = { version = "==2.8", build = "pyhd8ed1ab_0" }
sqlite = { version = "==3.50.2", build = "h79febb2_1" }
stack_data = { version = "==0.6.3", build = "pyhd8ed1ab_1" }
statsmodels = { version = "==0.14.5", build = "py310h307809b_0" }
terminado = { version = "==0.18.1", build = "pyh31c8845_0" }
threadpoolctl = { version = "==3.6.0", build = "pyhecae5ae_0" }
tinycss2 = { version = "==1.4.0", build = "pyhd8ed1ab_0" }
tk = { version = "==8.6.15", build = "hcd8a7d5_0" }
tomli = { version = "==2.2.1", build = "pyhe01879c_2" }
tornado = { version = "==6.5.2", build = "py310h7bdd564_1" }
traitlets = { version = "==5.14.3", build = "pyhd8ed1ab_1" }
types-python-dateutil = { version = "==2.9.0.20250822", build = "pyhd8ed1ab_0" }
typing-extensions = { version = "==4.15.0", build = "h396c80c_0" }
typing_extensions = { version = "==4.15.0", build = "pyhcf101f3_0" }
typing_utils = { version = "==0.1.0", build = "pyhd8ed1ab_1" }
tzdata = { version = "==2025b", build = "h04d1e81_0" }
uri-template = { version = "==1.3.0", build = "pyhd8ed1ab_1" }
urllib3 = { version = "==2.5.0", build = "pyhd8ed1ab_0" }
wcwidth = { version = "==0.2.14", build = "pyhd8ed1ab_0" }
webcolors = { version = "==24.11.1", build = "pyhd8ed1ab_0" }
webencodings = { version = "==0.5.1", build = "pyhd8ed1ab_3" }
websocket-client = { version = "==1.8.0", build = "pyhd8ed1ab_1" }
wheel = { version = "==0.45.1", build = "py310hca03da5_0" }
xz = { version = "==5.6.4", build = "h80987f9_1" }
yaml = { version = "==0.2.5", build = "h925e9cb_3" }
zeromq = { version = "==4.3.5", build = "h888dc83_9" }
zipp = { version = "==3.23.0", build = "pyhd8ed1ab_0" }
zlib = { version = "==1.3.1", build = "h5f15de7_0" }
zstandard = { version = "==0.25.0", build = "py310hf151d32_0" }
zstd = { version = "==1.5.7", build = "h6491c7d_2" }

[pypi-dependencies]
contourpy = "==1.3.2"
convertdate = "==2.4.0"
cycler = "==0.12.1"
dill = "==0.4.0"
ephem = "==4.2"
fonttools = "==4.60.0"
greykite = "==1.1.0"
hijri-converter = "==2.3.2.post1"
hijridate = "==2.3.0"
holidays = "==0.13"
holidays-ext = "==0.0.8"
iniconfig = "==2.1.0"
kiwisolver = "==1.4.9"
korean-lunar-calendar = "==0.3.1"
lunarcalendar-ext = "==0.0.1"
matplotlib = "==3.10.6"
numpy = "==1.26.0"
pandas = "==1.5.3"
pillow = "==11.3.0"
pluggy = "==1.6.0"
pymeeus = "==0.5.12"
pyparsing = "==3.2.5"
pytest = "==8.3.4"
scikit-learn = "==1.3.1"
scipy = "==1.15.1"
testfixtures = "==8.3.0"
tqdm = "==4.67.1"
